site_name: Machine Learning Operations
site_url: https://hogent.be
repo_url: https://github.com/HOGENT-MLOps/mlops-slides # Change this to your own Git repository (or leave it out).
copyright: Copyright &copy; HOGENT (<a href="https://hogent.be">https://hogent.be</a>)
nav:
  - Home: index.md
  - Study guide: 00-study-guide.md
  - Introduction: 00-introduction.md
  - Prerequisites: 00-prerequisites.md
  - "Lesson 1: docker": 01-docker.md
  - "Lesson 2: CI/CD": 02-ci-cd.md
  - "Lesson 3: ML workflow": 03-ml-workflow.pdf
  - "Lesson 4: kubernetes": 04-kubernetes.md
  - "Lesson 5: edge deployments": 05-edge-deployments.md
  - "Lesson 6: monitoring": 06-monitoring.md
theme:
  name: material # https://squidfunk.github.io/mkdocs-material/setup/
  favicon: https://hogenttin.github.io/cdn/favicon/favicon.ico
  features:
    - content.code.copy
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - toc.follow
  font:
    text: Montserrat
    code: Inconsolata
  logo: https://hogenttin.github.io/cdn/logo/HOGENT_Neg.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true
plugins:
  - git-authors:
      show_email_address: false # Disabled to prevent spam when your non-HOGENT e-mail address is used.
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      # Don't forget to adjust your CI pipeline to get all the info necessary:
      # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin?tab=readme-ov-file#note-when-using-build-environments
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
  - search
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
