---
name: compile
on:
  push:
    branches:
      - main
jobs:
  lint_and_check_links:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint markdown files
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: "**/*.md"
          config_file: .markdownlint.json
          dot: false

      - name: Check for dead links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          base-branch: "main"

  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Configure Git for GitHub
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.19.2"

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate slides
        env:
          TZ: Europe/Brussels # to get the correct date
        run: |
          make clean
          make all
          cp index.html gh-pages/index.html
          sed -ie "s#TIMESTAMP#$(date +'%d/%m/%Y %H:%M:%S')#" gh-pages/index.html

      - name: Push changes to gh-pages
        run: |
          cd gh-pages
          git add --all
          git commit --allow-empty -m "Publishing to gh-pages at $(date --utc --iso-8601=seconds)"
          git push origin gh-pages
